### ISSUE TITLE
Tailwind `dark:` selector not working

### ISSUE THREAD

**Issue by detronetdip** [shadcn-ui/ui#1147]
I am using `Popover` component and when I am applying dark at the top most level, entire website is changing to dark but the popover remains same.
```tsx
<PopoverContent sideOffset={-9} className="w-44 mr-2 p-2 rounded-md dark:bg-[#161B22] dark:border-border-dark">
```

This is what I have written where `border-border-dark` is a predefined style

**Comment by dan5py** [comment]
Hi @detronetdip, with `remains same` what you mean? Does the background change or it's just like in light mode?

**Comment by detronetdip** [comment]
@dan5py the background is just like in light mode, `dark:bg-[#161B22]` has no effect on that component.

**Comment by AmeerMuaviya** [comment]
> @dan5py the background is just like in light mode, `dark:bg-[#161B22]` has no effect on that component.

it should have effect. because in my case i've to use theme according to user preference in my app

**Comment by dan5py** [comment]
> @dan5py the background is just like in light mode, `dark:bg-[#161B22]` has no effect on that component.

If the `darkMode` is set to `class` in your `tailwind.config.js` you need to add the `dark` className to the `<html>` tag (or another component) to change to the dark color scheme.

**Comment by jaycedotbin** [comment]
This is the expected behavior because dark mode is toggled manually and does not rely on the media query feature, refer to the [dark mode](https://tailwindcss.com/docs/dark-mode) section in [tailwindcss](https://tailwindcss.com/) to know the behavior.

But basically, shadcn/ui turns on the `darkMode: ['class']` in `tailwind.config.js`, making the `dark:bg-[#161B22]` ineffective.

**Comment by detronetdip** [comment]
@dan5py  it worked when I added the `dark` class to the html but it was not not working otherwise
