### ISSUE TITLE
Question: Pairing shadcn/ui with a Carousel component...

### ISSUE THREAD

**Issue by mathewjordan** [shadcn-ui/ui#1206]
This is more of a question...

I'm seeking to pair [shadcn/ui](https://ui.shadcn.com/) with a Carousel (or slider depending on your nomenclature) component. Does anyone have recommendations for this? Requirements would be:

 - fully typed
 - react hooks
 - composable
 - highly accessible
 - unstyled (or capable of that)

**Comment by cerimorse** [comment]
I used [embla carousel](https://www.embla-carousel.com/) recently on a project with shadcn/ui. 

Meets quite a lot of your requirements and they have a [react](https://www.embla-carousel.com/get-started/react/) package too. The only thing I don't think is covered is accessibility. This [brief discussion](https://github.com/davidjerleke/embla-carousel/discussions/316) covers it but since then it looks like they're providing a [new project](https://github.com/davidjerleke/embla-carousel/issues/6#issuecomment-1626827751) that helps generate a carousel that includes accessibility.

If it's useful, here's how I [implemented](https://github.com/cerimorse/cerimorse.com/blob/main/src/components/common/carousel.js) embla carousel in my project alongside shadcn/ui. It isn't using TypeScript but hopefully gives a rough idea of what can be done.

**Comment by mathewjordan** [comment]
Thank you @cerimorse! That's very helpful. I might give it a try and see if it works. For context, I'll be using it in a component using an aging and bloated **[swiper.js](https://swiperjs.com/)** based implementation.
