### ISSUE TITLE
 "default" | "new-york" -  This cannot be changed after initialization.?  

### ISSUE THREAD

**Issue by archywillhe** [shadcn-ui/ui#1420]
So in the doc it says: " This cannot be changed after initialization" for style.

May I know why? And what if I want to change? What should I do? Clean install? 

Thanks

**Comment by limitless-dev** [comment]
That's because you need to re-install all of your `components/ui` again.
If you look at the `Input` component for example, it has different classNames based on style:
- https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/default/ui/input.tsx
- https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/new-york/ui/input.tsx

**Comment by josephna76** [comment]
It can be changed relatively easily as long as you haven't modified your custom ui. First change your components.json to use the new-work theme, then as limitless-dev said, delete the contents of your components/ui and re-install in bulk using `npx shadcn-ui@latest add`. I didn't have to modify my import paths to include /new-york/ in any of the routes.

<img width="658" alt="Screenshot 2023-09-01 at 9 22 07 AM" src="https://github.com/shadcn-ui/ui/assets/59426134/bf170d23-f98f-4ca5-8357-b4249baf5ac0">

**Comment by spellsaif** [comment]
Both the UI style is different so changing it will may cause you to lose your present components and things get worse if you have made customs changes to the components because that all will be gone. As @josephna76 said. If you haven't made any changes to your components reinstalling to another ui style will be no problem.

**Comment by archywillhe** [comment]
Aw I see; thanks! Gotcha! I haven't customized much & I just did a clean installed like [josephna76](https://github.com/josephna76) said. Working good!

**Comment by oluckyman** [comment]
would be nice to put this into docs to save googling time.
"What will happen if you change style after init?" and "What to do if you have to change the style after init?"
