### ISSUE TITLE
Prevent Dialog from Closing when clicking outside?

### ISSUE THREAD

**Issue by Dmytrocode** [shadcn-ui/ui#1712]
Is there any easy way to prevent this from happening by building my Dialog in another way or do I have to create this manually?

I want to prevent the user from closing the form when clicking outside of it

**Comment by anhcao142** [comment]
The Shadcn dialog uses the Radix UI dialog component. You can check the component usage here: https://www.radix-ui.com/primitives/docs/components/dialog

To prevent it from closing when clicking outside, you can handle the onInteractOutside prop to disable the effect.

**Comment by jaksiri** [comment]
On the Dialogue content component, you can set the onInteractOutside prop to a function to prevent the default behavior.
```
<DialogContent
        className=""
        onInteractOutside={(e) => {
          e.preventDefault();
        }}
```

**Comment by miquelvir** [comment]
@Dmytrocode please close the issue if its solved

**Comment by Oudwins** [comment]
I have this same issue except that I want to actually handle the events when one clicks outside the modal but if I don't prevent default it will close and if I do I can't handle the events....

Any solution?

**Comment by Dmytrocode** [comment]
> onInteractOutside={(e) => {
>           e.preventDefault();
>         }}

This did it. Thanks!

**Comment by harshilAmbliya** [comment]
THANK IT WAS HELPFULL

**Comment by stormynight9** [comment]
How to prevent the dialog from closing using the escape key?

**Comment by davidsonsns** [comment]
@stormynight9, to achieve this you can include the prop `onEscapeKeyDown`

ie.:

`<DialogContent onEscapeKeyDown={(e) => e.preventDefault()}>`

**Comment by aaronyyan** [comment]
> [@stormynight9](https://github.com/stormynight9), to achieve this you can include the prop `onEscapeKeyDown`
> 
> ie.:
> 
> `<DialogContent onEscapeKeyDown={(e) => e.preventDefault()}>`

don't work

**Comment by gvsakhil** [comment]
<DialogContent
        onEscapeKeyDown={(e) => e.preventDefault()}
        onPointerDownOutside={(e) => e.preventDefault()}
        onInteractOutside={(e) => e.preventDefault()}
      >

**Comment by yacineahmaich** [comment]
Maybe using the **Alert Dialog** instead will be a more better solution

**Comment by Bumboobee** [comment]
# Fix: Dialog onInteractOutside Triggering Incorrectly on Mobile

For those experiencing issues on mobile where `onInteractOutside` incorrectly recognizes inside clicks as outside clicks, here's the solution:

**Replace `onInteractOutside` with the more reliable `onPointerDownOutside` prop.**

## Why This Happens

The issue occurs because mobile touch events behave differently than desktop mouse events, causing false positive detections when users interact inside the dialog.

## Event Handler Comparison

### `onInteractOutside`
- **Purpose**: Fires when any interaction (mouse, touch, keyboard) happens outside the dialog
- **Mobile Issue**: Can be triggered by touch events that start inside but end outside due to scroll momentum, or complex touch gesture handling
- **Use Case**: General-purpose outside interaction detection

### `onPointerDownOutside` ✅ **Recommended**
- **Purpose**: Specifically fires when a pointer (mouse, finger, stylus) is pressed down outside the dialog  
- **Mobile Behavior**: More reliable on mobile because it only cares about the initial touch/click position
- **Use Case**: When you want to close on click/tap outside, regardless of what happens after

### `onFocusOutside`
- **Purpose**: Fires when focus moves outside the dialog
- **Use Case**: Keyboard navigation and accessibility scenarios

## Solution

**Before (problematic on mobile):**
```jsx
<DialogContent
  onOpenAutoFocus={(e) => e.preventDefault()}
  onCloseAutoFocus={(e) => e.preventDefault()}
  onInteractOutside={handleTentativaFechamento}
  onEscapeKeyDown={handleTentativaFechamento}
>
  {/* Dialog content */}
</DialogContent>
```

**After (mobile-friendly):**
```jsx
<DialogContent
  onOpenAutoFocus={(e) => e.preventDefault()}
  onCloseAutoFocus={(e) => e.preventDefault()}
  onPointerDownOutside={handleTentativaFechamento}
  onEscapeKeyDown={handleTentativaFechamento}
>
  {/* Dialog content */}
</DialogContent>
```

This simple change resolves the mobile touch detection issues while maintaining the expected behavior across all devices.

**Comment by TharukaDananjaya** [comment]
This hides the default shadcn/ui Dialog close button and prevents the dialog from closing when clicking the backdrop, using Radix’s onInteractOutside event.

```
<DialogContent 
   className="[&>button]:hidden" // hide default close (X) button 
   onInteractOutside={(e) => e.preventDefault()} // prevent backdrop/outside click from closing >
     Content 
</DialogContent>
```

**Comment by Jesus-David-Vidal-Ramirez** [comment]
Para vue con shadcn-vue
v-on:interact-outside="(e) => e.preventDefault()"

**Comment by ebulku** [comment]
This is not working for base-ui
