### ISSUE TITLE
When the drawer is closed, the scroll position undesirably jumps to the top of the page and then back again

### ISSUE THREAD

**Issue by yoannakr** [shadcn-ui/ui#2272]
When the drawer is closed, the scroll position undesirably jumps to the top of the page and then back again

https://github.com/shadcn-ui/ui/assets/55032687/ec4af7be-5a19-4840-8879-e7e3cec87829

**Comment by useit015** [comment]
facing the same issue here

**Comment by broisnischal** [comment]
I guess it is supposed to take the window height rather than the full page?

**Comment by begalinsaf** [comment]
https://github.com/shadcn-ui/ui/assets/145198186/f817cb37-f2b1-4f1b-bc50-d1cb0c2fdfba

same issue

**Comment by fluid-design-io** [comment]
> I think I found a solution, the problem is `scroll-behavior: smooth` from html class css attribute I just removed `scroll-behavior: smooth` or `scroll-smooth` from the html.
> 
>  Video.tanpa.judul.Dibuat.dengan.Clipchamp.mp4

@begalinsaf Yes, it seems to do the trick, I still want to preserve the smooth scroll behavior on my site so I added a simple hook to fix this issue:

```tsx
// use-scroll-behavior.tsx
import { useEffect } from 'react'

function useScrollBehavior(isOpen: boolean) {
  useEffect(() => {
    if (isOpen) {
      document.documentElement.style.scrollBehavior = 'auto'
    } else {
      setTimeout(() => {
        document.documentElement.style.scrollBehavior = 'smooth'
      }, 1000)
    }
  }, [isOpen])
}

export default useScrollBehavior
```

To use it:
```tsx
//...
const [open, setOpen] = useState(false)
useScrollBehavior(open)
return (
<Drawer open={open} onOpenChange={setOpen}>
  <DrawerTrigger asChild>
    <Button variant="outline">Button</Button>
  </DrawerTrigger>
  <DrawerContent>
    {/* ... */}
  </DrawerContent>
</Drawer>
)
}
```

**Comment by felipemenezes98** [comment]
I had the same issue and fixed it by setting document.documentElement.style.scrollBehavior to 'auto' when the drawer is open, and back to 'smooth' after a 400ms timeout when it closes. This short delay prevents unwanted scroll to the top on rapid interactions.

**Comment by yoannakr** [comment]
It looks like the issue was caused by vaul 
Take a look here: [vaul/issue](https://github.com/emilkowalski/vaul/issues/152)

**Comment by albertocubeddu** [comment]
The same is happening on the <Sheet>

**Comment by vitormarkis** [comment]
> The same is happening on the "Sheet" component.

Try updating vaul dependency, the issue is already closed and it was the solution for me at the time

**Comment by hedysnike** [comment]
can anyone post code ?

**Comment by maytees** [comment]
The `scroll-behavior: smooth` property was the issue for me, i just got around it by using responsive breakpoints, so mobile wont have smooth behavior. Very annoying issue with radix ui..

**Comment by eukosh** [comment]
Unfortunately in my case workaround for scroll-smooth did not work. This bug was hard to reproduce, I mean after adding a workaround for scroll smooth sometimes I had no issues, but after a few reloads, changing screen size the bug kept coming back. I have a sticky header that is dependent on scrolling, so drawer unreasonably messing with the scroll caused some pain here.

I ended up controlling drawer open/close state on my own without using `DrawerTrigger`, and it works well and I have no issues with the drawer, while having scroll-smooth always enabled on <html> tag.
```
const [isOpen, setIsOpen] = useState(false);

return (
    <Drawer open={isOpen} snapPoints={[1.05]}>
    {/* <DrawerTrigger asChild> */}
    {/* Controlling it with onClick handler because of the crazy scroll jump bug */}
	<Button variant="outlineTransparent" size="none" className="pl-1 pr-2 py-2.5" onClick={() => setIsOpen(true)}>
		Btn text
	</Button>
	{/* </DrawerTrigger> */}
	{/* Added custom prop onOverlayClick to close drawer on overlay click because of scroll jump bug */}
	<DrawerContent onOverlayClick={() => setIsOpen(false)} >
```

And passing onOverlayClick additional prop to close drawer when clicked on overlay
```
// extended with onOverlayClick because of the scroll jump bug
type DrawerContentProps = React.ComponentPropsWithoutRef<typeof DrawerPrimitive.Content> & {
  onOverlayClick?: () => void;
};
const DrawerContent = React.forwardRef<
  React.ElementRef<typeof DrawerPrimitive.Content>,
  DrawerContentProps
>(({ className, children, onOverlayClick, ...props }, ref) => (
  <DrawerPortal>
    <DrawerOverlay onClick={onOverlayClick} />
```

**Comment by ahmedtarekabd** [comment]
I solved it by making my navbar sticky, which is convenient in most cases, and worked for me just fine.

The problem with the `vaul` package is when we close the `Drawer`, it is [an expected behavior](https://github.com/corvudev/corvu/issues/55#:~:text=GiyoMoon%20commented%20on%20Aug%2031) according to the 
> Hey, this is expected behavior as we focus back on the trigger when the drawer closes for accessibility reasons.

Also for some reason `preventScrollRestoration` is not working, along with all other methods such as using `useState` to control the `open` state.

**Note:** I am using left direction for the drawer.
```tsx
        <Drawer
            open={isOpen}
            onOpenChange={setIsOpen}
            direction='left'
        >
            <DrawerTrigger className='flex items-center justify-center gap-2 lg:hidden'>
                <Menu className='h-6 w-6' />
                <span className='sr-only'>Menu</span>
            </DrawerTrigger>
            <DrawerContent
                className='left-0 right-auto top-0 mt-0 h-lvh w-3/4 rounded-none'
                onClick={(event: MouseEvent<HTMLDivElement>) => {
                    const target = event.target as HTMLElement
                    if (target.tagName === 'A') setIsOpen(false)
                }}
            >
           {/* Code... */}
        </Drawer>
```

**Comment by jayjeong8** [comment]
Sheet and Dialog are add `data-scroll-locked="1"` to body and use the style below.
In my case, the problem comes from `padding-top`. So I made `body padding-top`style to important style and fixed it.

![image](https://github.com/user-attachments/assets/f3f2b886-ca9a-4489-b6af-d2477f375cb8)

**Comment by frontend-wp** [comment]
Thank you eukosh, your solution actually woked and is simple

**Comment by Longvu1982** [comment]
Guys please help, it is still happening and I dont see anything related to the scroll-behavior: smooth


https://github.com/user-attachments/assets/2d0a4fc4-5932-45f8-aadf-74160344bff8

**Comment by robinjoh** [comment]
For me, setting noBodyStyles=true on the drawer component helped.

**Comment by hlebuska** [comment]
In my case, this happened on mobile due to ios weird behavior described here - https://stackoverflow.com/questions/28790889/css-how-to-prevent-scrolling-on-ios-safari

What I ended up doing was set modal={false}, writing custom scroll lock hook using ontouchmove + overflow: hidden, as well as implementing custom drawer overlay (modal={false} turns off the default one).

**Comment by LePoisson104** [comment]
For me all I need to do is remove the DrawerTrigger from the Drawer and pass the isOpen through props and this solved the scroll problem.
