### ISSUE TITLE
Dropdown Menu cannot be clicked when using useEffect render

### ISSUE THREAD

**Issue by tegarmonster** [shadcn-ui/ui#2285]
Hi, first of all,
I use Data Table and Dropdown Menu component
I can hover
![image](https://github.com/shadcn-ui/ui/assets/137743780/757288e2-2f4e-4ce5-9b28-e63b4fb079ab)
and then click the dropdown button
![Screenshot 2024-01-04 233137](https://github.com/shadcn-ui/ui/assets/137743780/2c7b3d35-f209-4dab-8602-d7b80a1fbcb4)

and I add useEffect hook for running the Progress Bar column, so it's dynamically change.. but the problem when using useEffect is, the Dropdown Menu cannot be clicked and show like this
https://www.loom.com/share/7a232c32102e4b83ab15104108fbbe2f?sid=1c3f6414-7179-44a8-8478-f1320067261c

how to fix that problem?

thanks

**Comment by Febin-Joseph** [comment]
The issue you're facing with the Dropdown Menu not being clickable when using the useEffect hook might be related to the rendering timing. Since you mentioned that you are using the useEffect hook for the Progress Bar column, it's possible that the rendering of the Dropdown Menu conflicts with the rendering of the Progress Bar.

**Comment by tegarmonster** [comment]
hi @Febin-Joseph .. yeah, the issue already solved now..
I change the interval time.. thanks
