### ISSUE TITLE
use-toast build error on deployment

### ISSUE THREAD

**Issue by tanjunior** [shadcn-ui/ui#284]
Works fine on dev environment but failed to build in vercel

![image](https://user-images.githubusercontent.com/11617693/235884252-2baa4b42-dc83-443a-b7d1-2fbdbfeb3f4c.png)

**Comment by dBianchii** [comment]
This is related to an eslint error. Check the use-toast.ts file and change line:
`interface Toast extends Omit<ToasterToast, "id"> {}`
To
'type Toast = Omit<ToasterToast, "id">'

@shadcn Do you think there is a reason to use interface? I was thinking maybe it would be an interesting idea to change all components to use type notation instead of interface notation when inheriting from other types without additional properties.

In case you are interested I can provide a PR for it later. Maybe would avoid ESlint issues like this for new users

**Comment by dBianchii** [comment]
@shadcn 
Also, there is a comon ESLint rule called consistent-type-imports
![image](https://user-images.githubusercontent.com/17372417/235937647-0643a5e8-9743-417c-b759-61369d418312.png)
![image](https://user-images.githubusercontent.com/17372417/235937819-713be17a-99fb-436e-8ed8-5d9749305c89.png)

I can also create dedicated PR in case it interests you to satisfy this eslint rule.

**Comment by tanjunior** [comment]
@dBianchii I was afraid that changing it to `type` would break things so I did this for now. real janky but it works.
```
interface Toast extends Omit<ToasterToast, "id"> {
    never?: never
}
```
