### ISSUE TITLE
[Bug]: Tooltip flickering when used for Checkbox with Label

### ISSUE THREAD

**Issue by mzahor** [shadcn-ui/ui#3073]
### Describe the bug

Tooltip is appearing for subsecond and then disappears when used for a checkbox with the label. It is important to **click on the label**, not the checkbox it self. Clicking on the checkbox itself works fine.

Code to reproduce the issue:
```ts
<TooltipProvider>
  <Tooltip>
    <TooltipTrigger>
      <div className="flex items-center space-x-2">
        <Checkbox id="terms" />
        <label
          htmlFor="terms"
          className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
        >
          Accept terms and conditions
        </label>
      </div>
    </TooltipTrigger>
    <TooltipContent>
      <p>Add to library</p>
    </TooltipContent>
  </Tooltip>
</TooltipProvider>;

```

### Affected component/components

Checkbox, Tooltip

### How to reproduce

1. Create a labeled checkbox with a tooltip.
2. Click on the label to change the checkbox state
3. Tooltip appears for a fraction of a second and then disappears (looks like flickering).
4. Click on the checkbox itself (not the label)
5. Tooltip doesn't appear (which is expected).

### Codesandbox/StackBlitz link

https://codesandbox.io/p/devbox/peaceful-maxwell-v7yqq4

### System Info

```bash
MacOS, Chrome, but it doesn't seem to be browser-related.
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by GustavoHenriqueP** [comment]
I've been affected by the same bug, but that occurs only on touch.

The same flickering happens even on the web page of the component in [shadcn](https://ui.shadcn.com/docs/components/tooltip) if you are in a touch device.

Looks like the problem is with Radix's Tooltip component itself.
When a touch event happens, for a fraction of second it changes its data-state attribute to **data-state="closed"** again and triggers the animations.
Since Radix components waits for an animation finish before unmounts, the animation of open and close happens and its displayed in the screen as that flickering.

The only solution I got was to remove the close animation and explicity animate the enter of the tooltip with **data-state="delayed-open"** and **data-state="instant-open"** in `<TooltipPrimitive.Content />` component:

`className={cn(
      'z-50 overflow-hidden rounded-md border bg-popover px-3 py-1.5 text-sm text-popover-foreground shadow-md data-[state=delayed-open]:animate-in data-[state=instant-open]:animate-in data-[state=delayed-open]:fade-in-0 data-[state=instant-open]:fade-in-0 data-[state=delayed-open]:zoom-in-95 data-[state=instant-open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2',
      className,
    )}`.

Maybe it fixes the same problem.

**Comment by mzahor** [comment]
Hi @GustavoHenriqueP, the fix worked, thanks a lot!
