### ISSUE TITLE
[Bug]: bunx init failed

### ISSUE THREAD

**Issue by herbertxy** [shadcn-ui/ui#3090]
### Describe the bug

```bash
❯ bunx --bun shadcn-ui@latest init
error: Script not found "shadcn-ui@latest"
❯ bun --version
1.0.30
```

### Affected component/components

init 

### How to reproduce

based on nextjs project 13.4, and this project was installed by bun i

### System Info

```bash
system: mac os 14
node 16\18
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Marviuz** [comment]
Try `bun x shadcn-ui@latest init`
I've found this from `bun -h` and it worked for adding components using `bun x shadcn-ui@latest add button` I thought it might work on init as well

**Comment by hashirnouman** [comment]
bunx --bun shadcn-ui@latest init
throws this error 
error: could not determine executable to run for package shadcn-ui

**Comment by Ali-Hamza-52** [comment]
### For initalization of shadcn use this command
`**bun x --bun shadcn-ui@latest init**`

### For add components use this commnad
`**bun x --bun shadcn-ui@latest add**`

[](https://ui.shadcn.com/docs/components/accordion)

**Comment by rizonkumar** [comment]
Subject: Issue adding any component with ```shadcn-ui```

Hi team,

I'm encountering an issue while trying to add the card component using ```shadcn-ui```. I've attached screenshots for reference.

Steps to reproduce:

I run the following command: ```bunx --bun shadcn-ui@latest add card``` (OR) ```bun x shadcn-ui@latest add card```

**Expected behavior:**
The card component should be added to my project using ```shadcn-ui.```

**Actual behavior:**
I receive the following error message: "could not determine executable to run for package shadcn-ui"

Additional information:

I've attempted to add the component using both ```npm``` and ```bun```, with the same error occurring.
Operating System: Windows 11
Node.js version:  ```v18.18.1```
Bun version: ```v1.1.29```
npm version: ```v10.8.3```

![image](https://github.com/user-attachments/assets/9ccd303c-7972-4791-b962-ed345ce3b3f4)
![image](https://github.com/user-attachments/assets/309d9d2a-60a5-4c78-bf8c-44d1e325b34d)

**Comment by somenath203** [comment]
If anyone is encoutering the error:

`could not determine executable to run for package shadcn-ui`

use the command:

`
bun x --bun shadcn@latest init
`

to initialize shadcn-ui with bun instead of the command:

`
bun x --bun shadcn-ui@latest init
`

and to add a component, use this command:

`
bun x --bun shadcn@latest add button
`

**Comment by VireshMeghanathi** [comment]
thank you very much

**Comment by 22GNUs** [comment]
> bun x --bun shadcn@latest init

So what's difference between `bun x --bun shadcn@latest init` and `bunx --bun shadcn@latest init`?

**Comment by YuraGB** [comment]
Hi.
I see that it doesn't work. I don't know if it is only for me.

![Image](https://github.com/user-attachments/assets/f4eb2e2b-23af-4c82-ade2-a442b721fb9e)

![Image](https://github.com/user-attachments/assets/67dd5cbf-ff0a-4fcc-8653-8ad6827d94cf)

**Comment by theanuragg** [comment]
![Image](https://github.com/user-attachments/assets/9147b0c8-8a58-431a-84d6-ce34b47f56ab) 


has anyone any idea  ??

**Comment by dillionverma** [comment]
also curious

related issue https://github.com/magicuidesign/magicui/issues/559

**Comment by truonghoangnhu** [comment]
The 'shadcn-ui' package is deprecated. Please use the 'shadcn' package instead.

**Comment by Pk13055** [comment]
Came across this later, but the issue still persists. I found using the [`bun`](https://bun.com/docs/cli/init) command works a lot better:

```sh
bun init --react=shadcn
```
