### ISSUE TITLE
[feat]: how to use colour

### ISSUE THREAD

**Issue by ravenkim** [shadcn-ui/ui#4750]
### Feature description

now: 
![image](https://github.com/user-attachments/assets/3ade7cba-fd2b-4d8e-a4db-9f68973d3392)

but if we use like this, code editor's plate does not work
![image](https://github.com/user-attachments/assets/49ad057f-8e2e-4410-b658-4210391da4c4)

by using hsl fuction we can change color easy!! 
![image](https://github.com/user-attachments/assets/f8681120-a4e5-4cb0-8a41-a317fcd119f7)

### Affected component/components

css

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by imMatheus** [comment]
The reason for this is due to how tailwind handles opacity. If you where to the `hsl` to the css variables, tailwind classes like `bg-background/50` (to add the background color with 50% opacity) would simply not work. 

Here is a very short and concise YT video that explains this [https://youtu.be/vIBKSmWAdIA?si=Yiz0sYzmb_NDYCQG](https://youtu.be/vIBKSmWAdIA?si=Yiz0sYzmb_NDYCQG)

So this is not really a Shadcn "issue", but more on Tailwind side

Hope that helps, and I think this issue can be closed now 🙏

**Comment by ravenkim** [comment]
background/50 this is nice to use! 

i hope plugin detect these color type too!
