### ISSUE TITLE
can't open sheet when trigger is my own component in "use client"

### ISSUE THREAD

**Issue by jlak0** [shadcn-ui/ui#4887]
### Describe the bug

I have created this demo repository
https://github.com/jlak0/sheetest

### Affected component/components

Sheet Trigger

### How to reproduce

when Sheet's trigger children is my own component and only when have "use client"  directives sheet can't open

### System Info

```bash
next.js 14.2.11
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by joseph0926** [comment]
Your custom button is currently not able to accept `ref`s
Try using `forwardRef` like below

```jsx
import { Button } from “@/components/ui/button”;
import { ComponentProps, forwardRef } from “react”;

export const MyButton = forwardRef<HTMLButtonElement, ComponentProps<“button”>>(
  ({ children, ...props }, ref) => {
    return (
      <Button ref={ref} {...props} variant=“outline”>
        {children}
      </Button>
    );
  }
);

MyButton.displayName = “MyButton”;

```

**Comment by joseph0926** [comment]
You used `asChild` in `SheetTrigger`
What this means is that you replace the tags already set by “shadcn” (or “Radix”) with the tags of the child component you defined
This will also override any `props` that are already defined
But your custom button component doesn't have any logic to accept `props'
Try adding this like below 

```jsx
import { Button } from “@/components/ui/button”;
import { ComponentProps, forwardRef } from “react”;

export const MyButton = forwardRef<HTMLButtonElement, ComponentProps<“button”>>(
  ({ children, ...props }, ref) => {
    return (
      <Button ref={ref} {...props} variant=“outline”>
        {children}
      </Button>
    );
  }
);

MyButton.displayName = “MyButton”;

```

---
I'm not sure, but I think this is fine for server components because they are rendered with everything already handed over by the server.
But the client component has to handle this process at runtime, and I think it's because it's not prepared to handle it, and that's where the problem comes in
So if you're going to use “use client”, I think you should explicitly take care of getting the props.

**Comment by jlak0** [comment]
> You used `asChild` in `SheetTrigger` What this means is that you replace the tags already set by “shadcn” (or “Radix”) with the tags of the child component you defined This will also override any `props` that are already defined But your custom button component doesn't have any logic to accept `props' Try adding this like below
> 
> ```js
> import { Button } from “@/components/ui/button”;
> import { ComponentProps, forwardRef } from “react”;
> 
> export const MyButton = forwardRef<HTMLButtonElement, ComponentProps<“button”>>(
>   ({ children, ...props }, ref) => {
>     return (
>       <Button ref={ref} {...props} variant=“outline”>
>         {children}
>       </Button>
>     );
>   }
> );
> 
> MyButton.displayName = “MyButton”;
> ```
> 
> I'm not sure, but I think this is fine for server components because they are rendered with everything already handed over by the server. But the client component has to handle this process at runtime, and I think it's because it's not prepared to handle it, and that's where the problem comes in So if you're going to use “use client”, I think you should explicitly take care of getting the props.

thank you all things works by adding props to my own component
